#9 GET /api/articles/:article_id/comments
ajknowlden1/NC-News-BE-Project pull request #10
Opened 2022-05-19 13:39 UTC by ajknowlden1

-creates the endpoint
-creates the model and controller
-tests the endpoint

2022-05-19 15:06 UTC, DCrawley94 requested changes
A few things for you to add but it's looking good Aaron!

2022-05-19 15:06 UTC, DCrawley94 commented on __tests__/app.test.js
> +              created_at: expect.any(String),
You could combine these first two tests if you like. Might be a litter more DRY :)

2022-05-19 15:06 UTC, DCrawley94 commented on __tests__/app.test.js
> +});
What if you have an article with no comments. What should happen then?

2022-05-20 09:49 UTC, bainesface commented on __tests__/app.test.js
> +  });
One more test Aaron, what if there are no comments because that article does not exist in the database?

2022-05-20 09:49 UTC, bainesface commented on __tests__/app.test.js
> +  });
Also be very careful when using a forEach to assert shape. It is not enough to check for an array, you also must check the length of the array. If the array is empty it would currently pass all of these tests even though there would be no comments returned when we expect some.

2022-05-20 10:52 UTC, dappernerddesigns requested changes
Hi Aaron, you still need to assert length when using forEach to check an array. Your second test (line251) would still pass even if the array were empty and we did actually expect a result.

2022-05-20 10:57 UTC, merged